version: 2

sources:
  - name: staging
    database:
      dtc-de-410519
      # For postgres:
      #database: production
    schema:
      data_all_homework4

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_trips
      - name:
          yellow_trips
      - name:
          fhv_data
          # freshness:
          # error_after: {count: 6, period: hour}
